### PR TITLE
Update getDailyRewards.js

### PR DESCRIPTION
**Pull request by 32ez01dude**
Adds a BUNCH of tokens (I just deleted the 500 and kept typing 9).

### CODE REVIEW

**Comment by Thing3487** [comment]
Stupid underage child which didn’t read the faq

**Comment by Thing3487** [comment]
@Minesraft2 Close this

**Comment by Girlwithnojob67** [comment]
where's the code

**Comment by Thing3487** [comment]
> where's the code

Stupid, no one wants ur code.

**Pull request closed without merging**
