### PR TITLE
updates

### PR DESCRIPTION
**Pull request by VillainsRule**
# Changes
**Describe what your changes/additions are and what they do:**
stop kids from asking about battl royable
plus you're already making autoplay

### CODE REVIEW

**Review by Wilke000 — APPROVED** [review]
Ye I've told Minescraft to do this before

**Review by Hlav10202 — APPROVED** [review]

**Comment by boss6565** [comment]
iii

**Comment by bailey1232543664** [comment]
can you give me 100 megalodons pls

**Comment by Minesraft2** [comment]
that's not possible

**Comment by bailey1232543664** [comment]
how do i get free blooket coins first day

**Comment by bailey1232543664** [comment]
it is my first day on GitHub can you give me unlimited coins pls

________________________________

**Comment by Minesraft2** [comment]
That's not possible

**Comment by bailey1232543664** [comment]
how can i

**Comment by orangemonkey01** [comment]
you cant its an insta ban

**Comment by orangemonkey01** [comment]
you can get daily rewards tho

**Comment by bailey1232543664** [comment]
i know

**Comment by orangemonkey01** [comment]
then why waste my time

**Review by rbcoder117 — APPROVED** [review]

**Pull request closed without merging**
