### PR TITLE
Auto-add gold

### PR DESCRIPTION
**Pull request by fowntain**
feel free to obfuscate idk

### CODE REVIEW

**Comment by fowntain** [comment]
poggers pull request

**Review by iParadoxian — CHANGES_REQUESTED** [review]
Why is it a global script if it only works in Gold Quest?

You could change the path from `unobfuscated/global/ ` to `unobfuscated/gold` since it doesn't work globally.

**Review by Greenlio — COMMENTED** [review]
- will be laggy
- shouldn't use reacthandler function, instead define a variable
- weird indention

**Review by BlooketHeck — CHANGES_REQUESTED** [review]
Why is it in global?

**Pull request closed without merging**
