### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Thing3487**
# Changes
**Update the how to. use on mobiile part in README.md**

### CODE REVIEW

**Comment by Thing3487** [comment]
> this doesn't work on iOS

Yes, it does

**Comment by Thing3487** [comment]
> this doesn't work on iOS

https://drive.google.com/file/d/1mEAHPlFR1X4TVcIyUVOpHoozP0VzBNiX/view?usp=sharing

**Comment by Jetnut** [comment]
Thank you Jayden Hwang

**Comment by Thing3487** [comment]
> Thank you Jayden Hwang

👍

**Review by Thing3487 — COMMENTED** [review]
Done

**Pull request closed without merging**
