### PR TITLE
Create createfolder.js

### PR DESCRIPTION
**Pull request by hackthegamezjj**
gets you a folder

### CODE REVIEW

**Comment by Thing3487** [comment]
GrEAt wOrK _COdEr_

**Comment by Thing3487** [comment]
And your fat ass is not permitted in the license. This is GooseterV, don’t think i’m a fool just like you

**Comment by Thing3487** [comment]
@Minesraft2  Close this

**Comment by Thing3487** [comment]
It’s stolen

**Comment by Thing3487** [comment]
@Minesraft2 Close

**Comment by Thing3487** [comment]
@GooseterV Look at this kid

**Comment by Minesraft2** [comment]
quit telling me to close things
I'm keeping this open on purpose as a suggestion

**Comment by Thing3487** [comment]
He stole it  from gooseterV

**Comment by Minesraft2** [comment]
goose is part of the council

**Comment by Thing3487** [comment]
> goose is part of the council

But @hackthegamezjj stole the code from gooseterV

**Comment by Minesraft2** [comment]
> > goose is part of the council
> 
> 
> 
> But @hackthegamezjj stole the code from gooseterV

he pasted 3 lines of code into a file and made a pull request

**Comment by Thing3487** [comment]
and also https://github.com/hackthegamezjj/Blooket-Hacks

**Comment by Thing3487** [comment]
> > > goose is part of the council
> > 
> > 
> > But @hackthegamezjj stole the code from gooseterV
> 
> he pasted 3 lines of code into a file and made a pull request

So??

**Comment by Minesraft2** [comment]
> > > > goose is part of the council
> 
> > > 
> 
> > > 
> 
> > > But @hackthegamezjj stole the code from gooseterV
> 
> > 
> 
> > he pasted 3 lines of code into a file and made a pull request
> 
> 
> 
> So??

I'm overlooking the fact that he copied someone's code in favor of the person he copied it from. I am going to keep this pull request open as a reminder to myself to add it to global eventually.

**Comment by Thing3487** [comment]
Ooooo

**Comment by Thing3487** [comment]
So that what you mean by “Goose is in the council”

**Comment by Thing3487** [comment]
Ok

**Comment by OGBlooketCheater** [comment]
uhh

**Comment by Greenlio** [comment]
yall need to shut up

**Pull request closed without merging**
