### PR TITLE
always frenzy

### PR DESCRIPTION
**Pull request by VillainsRule4000**
# Changes
**Describe what your changes/additions are and what they do:**
added an always frenzy script
the frenzy is always around 30s long, I assume you'll commit this yourself (as well as obfuscate, add update checker, etc)

### CODE REVIEW

**Comment by Wilke000** [comment]
Sweet

**Comment by Greenlio** [comment]
no

**Comment by Greenlio** [comment]
https://github.com/Minesraft2/Blooket-Cheats/blob/content/unobfuscated/fishing/alwaysFrenzy.js

**Comment by Greenlio** [comment]
jod can decide if he'll implement the into main

**Pull request closed without merging**
