### PR TITLE
Update gui.js

### PR DESCRIPTION
**Pull request by Nightmare-crypto**
Good

# Changes
**Describe what your changes/additions are and what they do:**

### CODE REVIEW

**Comment by BlooketFanBoy12** [comment]
It literally dosent do shit what did you actually change?

**Comment by orangemonkey01** [comment]
what?

**Review by Realswitzer — CHANGES_REQUESTED** [review]
No changes client facing, just removes license header. Only removes it from gui.js, no idea what the point is.
Can probably close PR.

**Comment by Minesraft2** [comment]
why would I remove the license part of the most popular script

**Comment by Nightmare-crypto** [comment]
> It literally dosent do shit what did you actually change?

Shut up

**Pull request closed without merging**
