### PR TITLE
get 995,000 tokens and 2,000 xp daily

### PR DESCRIPTION
**Pull request by hehetheblookethacker**
for fun

# Changes
**Describe what your changes/additions are and what they do:**

### CODE REVIEW

**Comment by Minesraft2** [comment]
That would suspend anyone who uses it

**Comment by 2xiq** [comment]
is there any way you can more tokens than the daily limit

**Comment by Minesraft2** [comment]
no

**Comment by 2xiq** [comment]
also why are there no hacks for battle royale

**Pull request closed without merging**
