### PR TITLE
me sad

### PR DESCRIPTION
**Pull request by bentyyyyy**
my freids are gitting into the new blacket and i cant i redisterd in school and meny more i was waiting for more than a week you guys the blacket staff are loosing a lot of players beacse of this plz fix it.......

### CODE REVIEW

**Comment by bentyyyyy** [comment]
bruh my freids are gitting into the new blacket and i cant i redisterd in school and meny more i was waiting for more than a week you guys the blacket staff are loosing a lot of players beacse of this plz fix it.......

**Comment by bentyyyyy** [comment]
my freids are gitting into the new blacket and i cant i redisterd in school and meny more i was waiting for more than a week you guys the blacket staff are loosing a lot of players beacse of this plz fix it.......

**Comment by Minesraft2** [comment]
This isn't something I can do anything about

**Comment by bentyyyyy** [comment]
ok

**Comment by bentyyyyy** [comment]
can you follow me plz

**Comment by fowntain** [comment]
> can you follow me plz

no.

**Comment by bentyyyyy** [comment]
why u so made

**Pull request closed without merging**
